#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Initialize (rebuild) a cloud-symlinks tar file from the symlinks currently on disk.

Use this when a tar file has been lost or deleted but the symbolic links themselves
still exist in the watched directory (e.g. the Zotero v7 storage folder). The tar is
just a serialization of those symlinks, so it can be regenerated by walking the
directory.

The archive it produces matches exactly what cloud_symlinks.py writes in its
SymLinksEventHandler.compress() method, so the running daemon will pick it up and
extract it identically:

  - recursive mode walks subdirectories and stores only symlinks, with arcnames
    relative to the watched directory (symlinks placed directly in the top-level
    directory are intentionally skipped, mirroring the daemon);
  - non-recursive mode stores every entry directly inside the directory.

By default it refuses to overwrite an existing tar file (pass --force to override),
so it is safe to run against a live setup.

Example (rebuild the deleted Zotero v7 archive):

  python3 init_tar.py \\
    -d /home/jaume/dropbox/seguretat/biblioteca/zotero-data/storage \\
    -f /home/jaume/dropbox/seguretat/biblioteca/zotero-tar/links-zotero-v7.tar.gz \\
    -r
"""
from __future__ import annotations

import argparse
import os
import sys
import tarfile


def collect_symlinks(directory: str, recursive: bool) -> list[str]:
    """
    Collect the arcnames (paths relative to ``directory``) to store in the tar file,
    reproducing the selection logic of SymLinksEventHandler.compress().

    :param directory: Path of the directory containing the symbolic links.
    :param recursive: When True, walk subdirectories collecting only symlinks;
        when False, take every entry directly inside ``directory``.
    :return: List of relative arcnames.
    """
    if not recursive:
        return list(os.listdir(directory))

    walked = list(os.walk(directory))
    folders = walked[1:]  # skip the top-level directory, matching the daemon
    symlinks: list[str] = []
    for basedir, _dirs, files in folders:
        for file in files:
            if os.path.islink(os.path.join(basedir, file)):
                symlinks.append(os.path.join(basedir.replace(directory, '')[1:], file))
    return symlinks


def build_tar(directory: str, tar_filename: str, recursive: bool) -> list[str]:
    """
    Write the tar file from the symlinks found in ``directory``.

    :param directory: Path of the directory containing the symbolic links.
    :param tar_filename: Destination path of the .tar.gz file to create.
    :param recursive: Whether to walk subdirectories (see collect_symlinks).
    :return: The list of arcnames that were added to the archive.
    """
    entries = collect_symlinks(directory, recursive)
    with tarfile.open(tar_filename, "w:gz") as tar:
        for entry in entries:
            # tarfile does not dereference symlinks by default, so the link itself
            # (its target path) is what gets stored -- exactly what we want.
            tar.add(os.path.join(directory, entry), arcname=entry)
    return entries


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('-d', '--dir', required=True,
                        help='Directory containing the symbolic links to archive')
    parser.add_argument('-f', '--tar-file', required=True,
                        help='Path of the .tar.gz file to create')
    parser.add_argument('-r', '--recursive', action='store_true',
                        help='Walk subdirectories collecting symlinks (Zotero v7+)')
    parser.add_argument('--force', action='store_true',
                        help='Overwrite the tar file if it already exists')
    args = parser.parse_args()

    if not os.path.isdir(args.dir):
        print('Directory {0} does not exist'.format(args.dir), file=sys.stderr)
        sys.exit(1)
    if os.path.exists(args.tar_file) and not args.force:
        print('Tar file {0} already exists; pass --force to overwrite'.format(args.tar_file),
              file=sys.stderr)
        sys.exit(1)

    tar_dir = os.path.dirname(os.path.abspath(args.tar_file))
    if not os.path.isdir(tar_dir):
        print('Destination directory {0} does not exist'.format(tar_dir), file=sys.stderr)
        sys.exit(1)

    entries = build_tar(args.dir, args.tar_file, args.recursive)
    print('Wrote {0} with {1} symlink(s).'.format(args.tar_file, len(entries)))


if __name__ == "__main__":
    main()
